
GameplayResourceDef {
	id				"cobalt_bio"
	localization_id "resource_name/cobalt_bio"
	bp  			"items/loot/resources/shard_cobalt_item"
	type 			"ammo_tower"
	icon			"gui/hud/resource_icons/cobalt_bio"
	bigger_icon		"gui/hud/resource_icons/cobalt_bio_bigger"
	hud_visible 	"never"
	order   		"8"
	specific_type	"biomass"
}

GameplayResourceDef {
	id				"palladium_bio"
	localization_id "resource_name/palladium_bio"
	bp  			"items/loot/resources/shard_palladium_item"
	type 			"ammo_tower"
	icon			"gui/hud/resource_icons/palladium_bio"
	bigger_icon		"gui/hud/resource_icons/palladium_bio_bigger"
	hud_visible 	"never"
	order   		"8"
	specific_type	"biomass"
}

GameplayResourceDef {
	id				"titanium_bio"
	localization_id "resource_name/titanium_bio"
	bp  			"items/loot/resources/shard_titanium_item"
	type 			"ammo_tower"
	icon			"gui/hud/resource_icons/titanium_bio"
	bigger_icon		"gui/hud/resource_icons/titanium_bio_bigger"
	hud_visible 	"never"
	order   		"8"
	specific_type	"biomass"
}

GameplayResourceDef {
	id				"uranium_bio"
	localization_id "resource_name/uranium_bio"
	bp  			"items/loot/resources/shard_uranium_ore_item"
	type 			"ammo_tower"
	icon			"gui/hud/resource_icons/uranium_bio"
	bigger_icon		"gui/hud/resource_icons/uranium_bio_bigger"
	hud_visible 	"never"
	order   		"8"
	specific_type	"biomass"
}

